name: pipeline-tools-1.0.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## bioconda packages, see above
  - fastqc=0.11.8
  - sra-tools=2.10.1
  - multiqc=1.7
  - samtools=1.9
  - star=2.6.1d             # Don't upgrade me - 2.7X indices incompatible with iGenomes.
  - trimmomatic=0.39